package com.ecnu.car_rent.dao;

import com.ecnu.car_rent.model.CarOrder;

import java.util.List;

public interface CarOrderMapper {

    List<CarOrder> selectCarOrderByGetName(String getName);//按id逆序

    List<CarOrder> selectCarOrderByHasName(String hasName);//按id逆序

    List<CarOrder> selectCarOrderByName(String name);//按id逆序

    List<CarOrder> selectCarOrdersByState(int state);//按id逆序

    List<CarOrder> selectAllCarOrders();//按id逆序


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_order
     *
     * @mbggenerated Tue Dec 19 14:39:15 CST 2017
     */
    int deleteByPrimaryKey(Integer carOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_order
     *
     * @mbggenerated Tue Dec 19 14:39:15 CST 2017
     */
    int insert(CarOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_order
     *
     * @mbggenerated Tue Dec 19 14:39:15 CST 2017
     */
    int insertSelective(CarOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_order
     *
     * @mbggenerated Tue Dec 19 14:39:15 CST 2017
     */
    CarOrder selectByPrimaryKey(Integer carOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_order
     *
     * @mbggenerated Tue Dec 19 14:39:15 CST 2017
     */
    int updateByPrimaryKeySelective(CarOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_order
     *
     * @mbggenerated Tue Dec 19 14:39:15 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(CarOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_order
     *
     * @mbggenerated Tue Dec 19 14:39:15 CST 2017
     */
    int updateByPrimaryKey(CarOrder record);
}


