package com.ecnu.car_rent.dao;

import com.ecnu.car_rent.model.News;

import java.util.List;

public interface NewsMapper {

    List<News> selectAllNews();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated Tue Dec 19 14:39:15 CST 2017
     */
    int deleteByPrimaryKey(Integer newsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated Tue Dec 19 14:39:15 CST 2017
     */
    int insert(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated Tue Dec 19 14:39:15 CST 2017
     */
    int insertSelective(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated Tue Dec 19 14:39:15 CST 2017
     */
    News selectByPrimaryKey(Integer newsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated Tue Dec 19 14:39:15 CST 2017
     */
    int updateByPrimaryKeySelective(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated Tue Dec 19 14:39:15 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated Tue Dec 19 14:39:15 CST 2017
     */
    int updateByPrimaryKey(News record);
}