package com.ecnu.car_rent.model;

import java.util.Date;

public class News {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_id
     *
     * @mbggenerated Tue Dec 19 14:39:15 CST 2017
     */
    private Integer newsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.title
     *
     * @mbggenerated Tue Dec 19 14:39:15 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.date
     *
     * @mbggenerated Tue Dec 19 14:39:15 CST 2017
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.link
     *
     * @mbggenerated Tue Dec 19 14:39:15 CST 2017
     */
    private String link;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.text
     *
     * @mbggenerated Tue Dec 19 14:39:15 CST 2017
     */
    private String text;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated Tue Dec 19 14:39:15 CST 2017
     */
    public News(Integer newsId, String title, Date date, String link, String text) {
        this.newsId = newsId;
        this.title = title;
        this.date = date;
        this.link = link;
        this.text = text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated Tue Dec 19 14:39:15 CST 2017
     */
    public News() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_id
     *
     * @return the value of news.news_id
     *
     * @mbggenerated Tue Dec 19 14:39:15 CST 2017
     */
    public Integer getNewsId() {
        return newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_id
     *
     * @param newsId the value for news.news_id
     *
     * @mbggenerated Tue Dec 19 14:39:15 CST 2017
     */
    public void setNewsId(Integer newsId) {
        this.newsId = newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.title
     *
     * @return the value of news.title
     *
     * @mbggenerated Tue Dec 19 14:39:15 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.title
     *
     * @param title the value for news.title
     *
     * @mbggenerated Tue Dec 19 14:39:15 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.date
     *
     * @return the value of news.date
     *
     * @mbggenerated Tue Dec 19 14:39:15 CST 2017
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.date
     *
     * @param date the value for news.date
     *
     * @mbggenerated Tue Dec 19 14:39:15 CST 2017
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.link
     *
     * @return the value of news.link
     *
     * @mbggenerated Tue Dec 19 14:39:15 CST 2017
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.link
     *
     * @param link the value for news.link
     *
     * @mbggenerated Tue Dec 19 14:39:15 CST 2017
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.text
     *
     * @return the value of news.text
     *
     * @mbggenerated Tue Dec 19 14:39:15 CST 2017
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.text
     *
     * @param text the value for news.text
     *
     * @mbggenerated Tue Dec 19 14:39:15 CST 2017
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }
}